import os
os.chdir(f"/home/xlab-app-center")
os.system(f"git clone -b totoro3 https://github.com/camenduru/ComfyUI /home/xlab-app-center/TotoroUI")
os.chdir(f"/home/xlab-app-center/TotoroUI")
os.system(f"git lfs install")
os.system(f"aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://www.modelscope.cn/models/AI-ModelScope/FLUX.1-dev/resolve/master/flux1-dev.safetensors -d /home/xlab-app-center/TotoroUI/models/unet -o flux1-dev.safetensors")
os.system(f"aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://www.modelscope.cn/models/AI-ModelScope/FLUX.1-dev/resolve/master/ae.safetensors -d /home/xlab-app-center/TotoroUI/models/vae -o ae.safetensors")
os.system(f"aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://www.modelscope.cn/models/mirror013/flux_text_encoders/resolve/master/flux_text_encoders/clip_l.safetensors -d /home/xlab-app-center/TotoroUI/models/clip -o clip_l.safetensors")
os.system(f"aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://www.modelscope.cn/models/mirror013/flux_text_encoders/resolve/master/flux_text_encoders/t5xxl_fp16.safetensors -d /home/xlab-app-center/TotoroUI/models/clip -o t5xxl_fp16.safetensors")
os.system(f"python launch.py")